name = "mail2ntfy"
main = "src/index.js"
compatibility_date = "2024-02-01"

[vars]
FORWARD_TO = "cacheall@domain.tld"
NTFY_ENDPOINT = "https://ntfy.sh/topic"
WHITELIST = { "address" = ["me@domain.tld"], "domain" = ["another.tld"] }
TZ = "Asia/Shanghai"
